<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Assignment02-ProductInventory.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\Assignment02-ProductInventory.Infrastructure.csproj" />
  </ItemGroup>

</Project>
