<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Assignment03-BankAccount.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\Assignment03-BankAccount.Infrastructure.csproj" />
  </ItemGroup>

</Project>
